# name: CI

on:
  push:
    branches:
      - master

name: Deploy Extension

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install --save-dev semantic-release semantic-release-vsce @emantic-release-changelog
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # In case you want to publish to Visual Studio Marketplace
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      # - name: Run semantice release
      #   run: |
      #     npx semantic-release
      #   working-directory: ${{ github.workspace }}

      # - name: Print package.json version (before)
      #   run: |
      #     echo "package.json version (before): $(jq -r .version package.json)"
      #   working-directory: ${{ github.workspace }}

      # - name: Fetch Latest Commit
      #   run: |
      #     git fetch
      #     git reset --hard origin/main
      # - name: Print package.json version (after)
      #   run: |
      #     echo "package.json version (after): $(jq -r .version package.json)"
      #   working-directory: ${{ github.workspace }}

      # - uses: lannonbr/vsce-action@4.0.0
      #   with:
      #     args: "publish -p $VSCE_TOKEN"
      #   env:
      #     VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
# # on:
# #   push:
# #     # Pattern matched against refs/tags
# #     tags:
# #       - '*'           # Push events to every tag not containing /
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 18.20
#     - run: npm install
#     - run: npm install -g @vscode/vsce
#     - run: vsce publish ${{ github.ref_name }}
